---
abstract: 'Look for a file in the current directory and upwards'
author:
  - 'Marcel Gruenauer <marcel@cpan.org>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 6.11
generated_by: 'Dist::Zilla version 1.100711'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: File-Find-Upwards
provides:
  File::Find::Upwards:
    file: lib/File/Find/Upwards.pm
    version: 1.100860
requires:
  Attribute::Memoize: 0
  Carp: 0
  English: 0
  Exporter: 0
  File::Find: 0
  File::Temp: 0
  FindBin: 0
  Path::Class: 0
  Scalar::Util: 0
  Test::More: 0.88
  perl: 5.008
resources:
  bugtracker: http://rt.cpan.org/Public/Dist/Display.html?Name=File-Find-Upwards
  homepage: http://search.cpan.org/dist/File-Find-Upwards/
  repository: http://github.com/hanekomu/File-Find-Upwards
version: 1.100860
